from pathlib import Path
import json
import unittest

ROOT = Path(__file__).resolve().parents[1]
TEXT = (ROOT / 'game' / 'scripts' / 'Main.gd').read_text(encoding='utf-8')


def block(name: str, next_name: str) -> str:
    start = TEXT.index(f'func {name}')
    end = TEXT.index(f'func {next_name}', start)
    return TEXT[start:end]


class ReleaseIntegrityContractTests(unittest.TestCase):
    def test_confirmation_is_bound_to_current_digest(self) -> None:
        self.assertIn(
            'confirmed_decision_digest = compute_decision_digest() if value else ""',
            TEXT,
        )
        self.assertIn(
            'confirmed_decision_digest != compute_decision_digest()',
            block('finalize_decision', 'raw_performance_score'),
        )
        self.assertIn(
            'decision_digest != confirmed_decision_digest',
            block('finalize_decision', 'raw_performance_score'),
        )

    def test_finalization_does_not_advance_decision_clock_after_confirmation(self) -> None:
        section = block('finalize_decision', 'raw_performance_score')
        self.assertNotIn('apply_pressure_tick(', section)

    def test_assessment_mode_withholds_authored_evidence_metadata(self) -> None:
        section = block('show_card_detail', 'toggle_card_mark')
        self.assertIn('if session_mode == "assessment":', section)
        self.assertIn('authored metadata labels are withheld', section)

    def test_assessment_mode_withholds_predecision_coaching(self) -> None:
        section = block('show_release_language', 'choose_release')
        self.assertIn('if session_mode == "assessment":', section)
        self.assertIn(
            'Assessment mode: coaching and safer-answer feedback are withheld until finalization.',
            section,
        )

    def test_aar_requires_confirmed_final_digest_equality(self) -> None:
        section = block('aar_payload_valid', 'export_aar_report')
        self.assertIn('final_digest == confirmed_digest', section)
        self.assertIn('final_digest == compute_decision_digest()', section)

    def test_validator_purges_generated_python_cache(self) -> None:
        validator = (ROOT / 'tools' / 'validate_repository.py').read_text(encoding='utf-8')
        self.assertIn('def remove_python_cache()', validator)
        self.assertIn('remove_python_cache()\n    env=dict(os.environ)', validator)

    def test_active_godot_metadata_uses_peace_os_identity(self) -> None:
        preset = (ROOT / 'game' / 'export_presets.cfg').read_text(encoding='utf-8')
        main = (ROOT / 'game' / 'scripts' / 'Main.gd').read_text(encoding='utf-8')
        self.assertIn('Peace_OS_Crisis_Room_v0.3.0-rc2.exe', preset)
        self.assertIn('application/copyright="Global AI Governance contributors; licensed under MIT"', preset)
        self.assertIn('Peace OS is the product name.', main)

    def test_release_inventory_excludes_python_cache(self) -> None:
        # Test discovery may legitimately create tests/__pycache__ in the working
        # tree. The release invariant is that generated bytecode is never part of
        # the controlled inventory or packaged source. Working-tree cache absence
        # remains enforced by tools/validate_repository.py under
        # PYTHONDONTWRITEBYTECODE=1.
        manifest = json.loads((ROOT / 'MANIFEST.json').read_text(encoding='utf-8'))
        paths = [entry['path'] for entry in manifest['files']]
        inventory = '\n'.join(paths)
        self.assertNotIn('__pycache__', inventory)
        self.assertFalse(any(path.endswith(('.pyc', '.pyo')) for path in paths))
        sums = (ROOT / 'SHA256SUMS.txt').read_text(encoding='utf-8')
        self.assertNotIn('__pycache__', sums)
        self.assertNotIn('.pyc', sums)
        self.assertNotIn('.pyo', sums)


if __name__ == '__main__':
    unittest.main()
